site_name: Lacking
site_url: http://mokiat.com/lacking
repo_url: https://github.com/mokiat/lacking/
theme:
  name: material
nav:
  - Home: index.md
  - Examples: examples.md
  - Getting Started: getting-started.md
  - User's Guide:
    - Application: manual/application/index.md
    - Audio: manual/audio/index.md
    - ECS: manual/ecs/index.md
    - Game: manual/game/index.md
    - Graphics:
      - Shader: manual/graphics/shader.md
    - Rendering: manual/rendering/index.md
    - User Interface: manual/user-interface/index.md
  - Internals:
    - Physics:
      - Overview: development/physics/index.md
      - References: development/physics/references.md
      - Theory:
        - Principles: development/physics/theory/principles.md
        - Terminology: development/physics/theory/terminology.md
        - Equations: development/physics/theory/equations.md
        - Effective Mass: development/physics/theory/effective-mass.md
        - Moment of Inertia: development/physics/theory/moment-of-inertia.md
      - Derivations:
        - Impulse: development/physics/derivations/impulse-derivation.md
        - Effective Mass: development/physics/derivations/effective-mass-derivation.md
    - Math:
      - Vectors: development/math/vectors.md
      - Derivatives: development/math/derivatives.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
