package lsl_test

import (
	"slices"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/mokiat/lacking/game/graphics/lsl"
)

var _ = Describe("Tokenizer", func() {
	token := func(kind lsl.TokenType, value string, pos lsl.Position) lsl.Token {
		return lsl.Token{
			Type:  kind,
			Value: value,
			Pos:   pos,
		}
	}

	DescribeTable("Next", func(inSource string, expectedTokens []lsl.Token) {
		outTokens := slices.Collect(lsl.Tokenize(inSource))
		Expect(outTokens).To(Equal(expectedTokens))
	},
		Entry("blank source",
			openTestFile("tokenizer-next", "blank.lsl"),
			nil,
		),
		Entry("empty source",
			openTestFile("tokenizer-next", "empty.lsl"),
			nil,
		),
		Entry("comment",
			openTestFile("tokenizer-next", "comment.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),
				token(lsl.TokenTypeComment, "This is a comment", lsl.At(2, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 21)),
				token(lsl.TokenTypeComment, "This is another comment", lsl.At(3, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 26)),
			},
		),
		Entry("block declaration",
			openTestFile("tokenizer-next", "block-declaration.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),
				token(lsl.TokenTypeIdentifier, "uniforms", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, "{", lsl.At(2, 10)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 11)),
				token(lsl.TokenTypeOperator, "}", lsl.At(3, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 2)),
				token(lsl.TokenTypeIdentifier, "uniforms", lsl.At(4, 1)),
				token(lsl.TokenTypeOperator, "{", lsl.At(4, 9)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(4, 10)),
				token(lsl.TokenTypeOperator, "}", lsl.At(5, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(5, 2)),
			},
		),
		Entry("block content declaration",
			openTestFile("tokenizer-next", "block-content-declaration.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),
				token(lsl.TokenTypeIdentifier, "color", lsl.At(2, 1)),
				token(lsl.TokenTypeIdentifier, "vec3", lsl.At(2, 7)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 11)),
				token(lsl.TokenTypeIdentifier, "intensity", lsl.At(3, 1)),
				token(lsl.TokenTypeIdentifier, "float", lsl.At(3, 13)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 18)),
			},
		),
		Entry("function declaration",
			openTestFile("tokenizer-next", "function-declaration.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "func", lsl.At(2, 1)),
				token(lsl.TokenTypeIdentifier, "hello", lsl.At(2, 6)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 11)),
				token(lsl.TokenTypeIdentifier, "a", lsl.At(2, 12)),
				token(lsl.TokenTypeIdentifier, "vec3", lsl.At(2, 14)),
				token(lsl.TokenTypeOperator, ",", lsl.At(2, 18)),
				token(lsl.TokenTypeIdentifier, "b", lsl.At(2, 20)),
				token(lsl.TokenTypeIdentifier, "float", lsl.At(2, 22)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 27)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 29)),
				token(lsl.TokenTypeIdentifier, "vec4", lsl.At(2, 30)),
				token(lsl.TokenTypeOperator, ",", lsl.At(2, 34)),
				token(lsl.TokenTypeIdentifier, "float", lsl.At(2, 36)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 41)),
				token(lsl.TokenTypeOperator, "{", lsl.At(2, 43)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 44)),
				token(lsl.TokenTypeOperator, "}", lsl.At(3, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 2)),

				token(lsl.TokenTypeIdentifier, "func", lsl.At(4, 1)),
				token(lsl.TokenTypeIdentifier, "world", lsl.At(4, 6)),
				token(lsl.TokenTypeOperator, "(", lsl.At(4, 11)),
				token(lsl.TokenTypeOperator, ")", lsl.At(4, 12)),
				token(lsl.TokenTypeIdentifier, "vec3", lsl.At(4, 14)),
				token(lsl.TokenTypeOperator, "{", lsl.At(4, 19)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(4, 20)),
				token(lsl.TokenTypeOperator, "}", lsl.At(5, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(5, 2)),

				token(lsl.TokenTypeIdentifier, "func", lsl.At(6, 1)),
				token(lsl.TokenTypeIdentifier, "test", lsl.At(6, 6)),
				token(lsl.TokenTypeOperator, "(", lsl.At(6, 10)),
				token(lsl.TokenTypeOperator, ")", lsl.At(6, 11)),
				token(lsl.TokenTypeOperator, "{", lsl.At(6, 13)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(6, 14)),
				token(lsl.TokenTypeOperator, "}", lsl.At(7, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(7, 2)),
			},
		),
		Entry("var declaration",
			openTestFile("tokenizer-next", "var-declaration.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "var", lsl.At(2, 1)),
				token(lsl.TokenTypeIdentifier, "a", lsl.At(2, 5)),
				token(lsl.TokenTypeIdentifier, "vec3", lsl.At(2, 7)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 11)),

				token(lsl.TokenTypeIdentifier, "var", lsl.At(3, 1)),
				token(lsl.TokenTypeIdentifier, "b", lsl.At(3, 5)),
				token(lsl.TokenTypeIdentifier, "float", lsl.At(3, 7)),
				token(lsl.TokenTypeOperator, "=", lsl.At(3, 13)),
				token(lsl.TokenTypeNumber, "1.0", lsl.At(3, 15)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 18)),

				token(lsl.TokenTypeIdentifier, "var", lsl.At(4, 1)),
				token(lsl.TokenTypeIdentifier, "c", lsl.At(4, 5)),
				token(lsl.TokenTypeIdentifier, "float", lsl.At(4, 7)),
				token(lsl.TokenTypeOperator, "=", lsl.At(4, 13)),
				token(lsl.TokenTypeOperator, "-", lsl.At(4, 15)),
				token(lsl.TokenTypeNumber, "1.0", lsl.At(4, 16)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(4, 19)),
			},
		),
		Entry("field access",
			openTestFile("tokenizer-next", "field-access.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "color", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, ".", lsl.At(2, 6)),
				token(lsl.TokenTypeIdentifier, "x", lsl.At(2, 7)),
				token(lsl.TokenTypeOperator, "=", lsl.At(2, 8)),
				token(lsl.TokenTypeNumber, "1.0", lsl.At(2, 9)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 12)),

				token(lsl.TokenTypeIdentifier, "color", lsl.At(3, 1)),
				token(lsl.TokenTypeOperator, ".", lsl.At(3, 6)),
				token(lsl.TokenTypeIdentifier, "y", lsl.At(3, 7)),
				token(lsl.TokenTypeOperator, "=", lsl.At(3, 8)),
				token(lsl.TokenTypeOperator, "-", lsl.At(3, 9)),
				token(lsl.TokenTypeIdentifier, "color", lsl.At(3, 10)),
				token(lsl.TokenTypeOperator, ".", lsl.At(3, 15)),
				token(lsl.TokenTypeIdentifier, "x", lsl.At(3, 16)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 17)),
			},
		),
		Entry("numeric expression",
			openTestFile("tokenizer-next", "numeric-expression.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "x", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, "=", lsl.At(2, 3)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 5)),
				token(lsl.TokenTypeNumber, "7.1", lsl.At(2, 6)),
				token(lsl.TokenTypeOperator, "*", lsl.At(2, 10)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 12)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 13)),
				token(lsl.TokenTypeNumber, "13", lsl.At(2, 14)),
				token(lsl.TokenTypeOperator, "/", lsl.At(2, 17)),
				token(lsl.TokenTypeNumber, "2", lsl.At(2, 19)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 20)),
				token(lsl.TokenTypeOperator, "%", lsl.At(2, 21)),
				token(lsl.TokenTypeNumber, "5.5", lsl.At(2, 22)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 25)),
				token(lsl.TokenTypeOperator, "+", lsl.At(2, 26)),
				token(lsl.TokenTypeNumber, "3.0", lsl.At(2, 27)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 30)),
				token(lsl.TokenTypeOperator, "-", lsl.At(2, 32)),
				token(lsl.TokenTypeNumber, "5", lsl.At(2, 34)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 35)),
			},
		),
		Entry("bit-wise expression",
			openTestFile("tokenizer-next", "bit-wise-expression.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "x", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, "=", lsl.At(2, 3)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 5)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 6)),
				token(lsl.TokenTypeNumber, "6", lsl.At(2, 7)),
				token(lsl.TokenTypeOperator, "<<", lsl.At(2, 9)),
				token(lsl.TokenTypeNumber, "1", lsl.At(2, 12)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 13)),
				token(lsl.TokenTypeOperator, "^", lsl.At(2, 15)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 17)),
				token(lsl.TokenTypeNumber, "8", lsl.At(2, 18)),
				token(lsl.TokenTypeOperator, ">>", lsl.At(2, 20)),
				token(lsl.TokenTypeNumber, "2", lsl.At(2, 23)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 24)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 25)),
				token(lsl.TokenTypeOperator, "|", lsl.At(2, 27)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 29)),
				token(lsl.TokenTypeNumber, "3", lsl.At(2, 30)),
				token(lsl.TokenTypeOperator, "&", lsl.At(2, 32)),
				token(lsl.TokenTypeNumber, "5", lsl.At(2, 34)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 35)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 36)),
			},
		),
		Entry("boolean expression",
			openTestFile("tokenizer-next", "boolean-expression.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "x", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, "=", lsl.At(2, 3)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 5)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 6)),
				token(lsl.TokenTypeIdentifier, "x", lsl.At(2, 7)),
				token(lsl.TokenTypeOperator, ".", lsl.At(2, 8)),
				token(lsl.TokenTypeIdentifier, "z", lsl.At(2, 9)),
				token(lsl.TokenTypeOperator, "==", lsl.At(2, 11)),
				token(lsl.TokenTypeIdentifier, "z", lsl.At(2, 14)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 15)),
				token(lsl.TokenTypeOperator, "&&", lsl.At(2, 17)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 20)),
				token(lsl.TokenTypeNumber, "5", lsl.At(2, 21)),
				token(lsl.TokenTypeOperator, "!=", lsl.At(2, 23)),
				token(lsl.TokenTypeNumber, "4", lsl.At(2, 26)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 27)),
				token(lsl.TokenTypeOperator, "&&", lsl.At(2, 29)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 32)),
				token(lsl.TokenTypeNumber, "1", lsl.At(2, 33)),
				token(lsl.TokenTypeOperator, "<", lsl.At(2, 35)),
				token(lsl.TokenTypeNumber, "2", lsl.At(2, 37)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 38)),
				token(lsl.TokenTypeOperator, "&&", lsl.At(2, 40)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 43)),
				token(lsl.TokenTypeNumber, "1.1", lsl.At(2, 44)),
				token(lsl.TokenTypeOperator, ">", lsl.At(2, 47)),
				token(lsl.TokenTypeNumber, "3", lsl.At(2, 48)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 49)),
				token(lsl.TokenTypeOperator, "&&", lsl.At(2, 51)),
				token(lsl.TokenTypeIdentifier, "true", lsl.At(2, 54)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 58)),
				token(lsl.TokenTypeOperator, "||", lsl.At(2, 60)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 63)),
				token(lsl.TokenTypeIdentifier, "false", lsl.At(2, 64)),
				token(lsl.TokenTypeOperator, "&&", lsl.At(2, 69)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 71)),
				token(lsl.TokenTypeNumber, "5", lsl.At(2, 72)),
				token(lsl.TokenTypeOperator, ">=", lsl.At(2, 74)),
				token(lsl.TokenTypeNumber, "9", lsl.At(2, 77)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 78)),
				token(lsl.TokenTypeOperator, "&&", lsl.At(2, 79)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 82)),
				token(lsl.TokenTypeNumber, "2", lsl.At(2, 83)),
				token(lsl.TokenTypeOperator, "<=", lsl.At(2, 85)),
				token(lsl.TokenTypeNumber, "1", lsl.At(2, 88)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 89)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 90)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 91)),

				token(lsl.TokenTypeIdentifier, "y", lsl.At(3, 1)),
				token(lsl.TokenTypeOperator, "=", lsl.At(3, 3)),
				token(lsl.TokenTypeOperator, "!", lsl.At(3, 5)),
				token(lsl.TokenTypeIdentifier, "true", lsl.At(3, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 10)),
			},
		),
		Entry("assignments",
			openTestFile("tokenizer-next", "assignments.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "a", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, "=", lsl.At(2, 2)),
				token(lsl.TokenTypeNumber, "13", lsl.At(2, 3)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 5)),

				token(lsl.TokenTypeIdentifier, "b", lsl.At(3, 1)),
				token(lsl.TokenTypeOperator, "=", lsl.At(3, 3)),
				token(lsl.TokenTypeNumber, "55.3", lsl.At(3, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 9)),

				token(lsl.TokenTypeIdentifier, "c", lsl.At(4, 1)),
				token(lsl.TokenTypeOperator, "+=", lsl.At(4, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(4, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(4, 7)),

				token(lsl.TokenTypeIdentifier, "d", lsl.At(5, 1)),
				token(lsl.TokenTypeOperator, "+=", lsl.At(5, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(5, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(5, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(5, 6)),

				token(lsl.TokenTypeIdentifier, "e", lsl.At(6, 1)),
				token(lsl.TokenTypeOperator, "-=", lsl.At(6, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(6, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(6, 7)),

				token(lsl.TokenTypeIdentifier, "f", lsl.At(7, 1)),
				token(lsl.TokenTypeOperator, "-=", lsl.At(7, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(7, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(7, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(7, 6)),

				token(lsl.TokenTypeIdentifier, "g", lsl.At(8, 1)),
				token(lsl.TokenTypeOperator, "*=", lsl.At(8, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(8, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(8, 7)),

				token(lsl.TokenTypeIdentifier, "h", lsl.At(9, 1)),
				token(lsl.TokenTypeOperator, "*=", lsl.At(9, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(9, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(9, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(9, 6)),

				token(lsl.TokenTypeIdentifier, "i", lsl.At(10, 1)),
				token(lsl.TokenTypeOperator, "/=", lsl.At(10, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(10, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(10, 7)),

				token(lsl.TokenTypeIdentifier, "j", lsl.At(11, 1)),
				token(lsl.TokenTypeOperator, "/=", lsl.At(11, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(11, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(11, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(11, 6)),

				token(lsl.TokenTypeIdentifier, "k", lsl.At(12, 1)),
				token(lsl.TokenTypeOperator, "%=", lsl.At(12, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(12, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(12, 7)),

				token(lsl.TokenTypeIdentifier, "l", lsl.At(13, 1)),
				token(lsl.TokenTypeOperator, "%=", lsl.At(13, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(13, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(13, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(13, 6)),

				token(lsl.TokenTypeIdentifier, "m", lsl.At(14, 1)),
				token(lsl.TokenTypeOperator, ">>=", lsl.At(14, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(14, 7)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(14, 8)),

				token(lsl.TokenTypeIdentifier, "n", lsl.At(15, 1)),
				token(lsl.TokenTypeOperator, ">>=", lsl.At(15, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(15, 5)),
				token(lsl.TokenTypeNumber, "5", lsl.At(15, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(15, 7)),

				token(lsl.TokenTypeIdentifier, "o", lsl.At(16, 1)),
				token(lsl.TokenTypeOperator, "<<=", lsl.At(16, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(16, 7)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(16, 8)),

				token(lsl.TokenTypeIdentifier, "p", lsl.At(17, 1)),
				token(lsl.TokenTypeOperator, "<<=", lsl.At(17, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(17, 5)),
				token(lsl.TokenTypeNumber, "5", lsl.At(17, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(17, 7)),

				token(lsl.TokenTypeIdentifier, "q", lsl.At(18, 1)),
				token(lsl.TokenTypeOperator, "&=", lsl.At(18, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(18, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(18, 7)),

				token(lsl.TokenTypeIdentifier, "r", lsl.At(19, 1)),
				token(lsl.TokenTypeOperator, "&=", lsl.At(19, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(19, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(19, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(19, 6)),

				token(lsl.TokenTypeIdentifier, "s", lsl.At(20, 1)),
				token(lsl.TokenTypeOperator, "^=", lsl.At(20, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(20, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(20, 7)),

				token(lsl.TokenTypeIdentifier, "t", lsl.At(21, 1)),
				token(lsl.TokenTypeOperator, "^=", lsl.At(21, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(21, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(21, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(21, 6)),

				token(lsl.TokenTypeIdentifier, "u", lsl.At(22, 1)),
				token(lsl.TokenTypeOperator, "|=", lsl.At(22, 3)),
				token(lsl.TokenTypeNumber, "5", lsl.At(22, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(22, 7)),

				token(lsl.TokenTypeIdentifier, "v", lsl.At(23, 1)),
				token(lsl.TokenTypeOperator, "|=", lsl.At(23, 2)),
				token(lsl.TokenTypeOperator, "-", lsl.At(23, 4)),
				token(lsl.TokenTypeNumber, "5", lsl.At(23, 5)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(23, 6)),

				token(lsl.TokenTypeIdentifier, "w", lsl.At(24, 1)),
				token(lsl.TokenTypeOperator, ":=", lsl.At(24, 3)),
				token(lsl.TokenTypeNumber, "8", lsl.At(24, 6)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(24, 7)),

				token(lsl.TokenTypeIdentifier, "x", lsl.At(25, 1)),
				token(lsl.TokenTypeOperator, ":=", lsl.At(25, 2)),
				token(lsl.TokenTypeNumber, "8", lsl.At(25, 4)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(25, 5)),
			},
		),
		Entry("func invocation",
			openTestFile("tokenizer-next", "func-invocation.lsl"),
			[]lsl.Token{
				token(lsl.TokenTypeNewLine, "\n", lsl.At(1, 1)),

				token(lsl.TokenTypeIdentifier, "doSomething", lsl.At(2, 1)),
				token(lsl.TokenTypeOperator, "(", lsl.At(2, 12)),
				token(lsl.TokenTypeNumber, "15.55", lsl.At(2, 13)),
				token(lsl.TokenTypeOperator, ",", lsl.At(2, 18)),
				token(lsl.TokenTypeNumber, "10", lsl.At(2, 20)),
				token(lsl.TokenTypeOperator, ",", lsl.At(2, 22)),
				token(lsl.TokenTypeIdentifier, "someVar", lsl.At(2, 24)),
				token(lsl.TokenTypeOperator, ")", lsl.At(2, 31)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(2, 32)),

				token(lsl.TokenTypeIdentifier, "var", lsl.At(3, 1)),
				token(lsl.TokenTypeIdentifier, "a", lsl.At(3, 5)),
				token(lsl.TokenTypeIdentifier, "vec4", lsl.At(3, 7)),
				token(lsl.TokenTypeOperator, "=", lsl.At(3, 12)),
				token(lsl.TokenTypeIdentifier, "calculate", lsl.At(3, 14)),
				token(lsl.TokenTypeOperator, "(", lsl.At(3, 23)),
				token(lsl.TokenTypeOperator, ")", lsl.At(3, 24)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(3, 25)),

				token(lsl.TokenTypeIdentifier, "var", lsl.At(4, 1)),
				token(lsl.TokenTypeIdentifier, "b", lsl.At(4, 5)),
				token(lsl.TokenTypeIdentifier, "float", lsl.At(4, 7)),
				token(lsl.TokenTypeOperator, "=", lsl.At(4, 13)),
				token(lsl.TokenTypeIdentifier, "sum", lsl.At(4, 15)),
				token(lsl.TokenTypeOperator, "(", lsl.At(4, 18)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(4, 19)),
				token(lsl.TokenTypeNumber, "115.3", lsl.At(5, 3)),
				token(lsl.TokenTypeOperator, ",", lsl.At(5, 8)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(5, 9)),
				token(lsl.TokenTypeIdentifier, "abs", lsl.At(6, 3)),
				token(lsl.TokenTypeOperator, "(", lsl.At(6, 6)),
				token(lsl.TokenTypeOperator, "-", lsl.At(6, 7)),
				token(lsl.TokenTypeNumber, "15", lsl.At(6, 8)),
				token(lsl.TokenTypeOperator, ")", lsl.At(6, 10)),
				token(lsl.TokenTypeOperator, ",", lsl.At(6, 11)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(6, 12)),
				token(lsl.TokenTypeOperator, ")", lsl.At(7, 1)),
				token(lsl.TokenTypeNewLine, "\n", lsl.At(7, 2)),
			},
		),
	)
})
